env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: kiln
    main: .
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X "main.version={{ .Tag }} ({{ .Os }}/{{ .Arch }})" -X "main.commit={{ .ShortCommit }}" -X "main.date={{ .Date }}"

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
