name: Go Tests

on:
  push:
    branches: ['**']
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23', '1.24.x']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{ matrix.go }}
      - run: make test
